import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="border-b border-[#2E2E32] p-4">
          <div className="container mx-auto flex gap-4">
            <Link href="/" className="text-white hover:text-gray-300">首页</Link>
            <Link href="/table" className="text-white hover:text-gray-300">表格</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
